apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-devops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: flask-devops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-devops-service
            port:
              number: 5000

